export const SectionItems = [
  {
    id: 1,
    title: "Model 3",
    src: "/model3.avif",
    subtitle: "Starting at $32,740",
    bt1: "Explore inventory",
    btn2: "Custom order",
  },
  {
    id: 2,
    title: "Model Y",
    src: "/modely.avif",
    subtitle: "Starting at $40,240",
    bt1: "Explore inventory",
    btn2: "Custom order",
  },
  {
    id: 3,
    title: "Model S",
    src: "/modelS.avif",
    subtitle: "Explore Inventory",
    bt1: "Custom order",
    btn2: "Demo Drive",
  },
  {
    id: 4,
    title: "Model X",
    src: "/modelX.avif",
    subtitle: "Explore Inventory",
    bt1: "Custom order",
    btn2: "Demo Drive",
  },
  {
    id: 5,
    title: "Solar Panels",
    src: "/solarPanel.avif",
    subtitle: "Schedule a Virtual Consultation",
    bt1: "Order Now",
    btn2: "Learn More",
  },
  {
    id: 6,
    title: "Solar Roof",
    src: "/solarRoof.avif",
    subtitle: "Produce Clean Energy From Your Roof",
    bt1: "Order Now",
    btn2: "Learn More",
  },
  {
    id: 7,
    title: "Powerwall",
    src: "/powerwall.avif",
    bt1: "Order Now",
    btn2: "Learn More",
  },
  {
    id: 8,
    title: "Accessories",
    src: "accessories.avif",
    bt1: "Order Now",
    btn2: "Learn More",
  },
];
